# Generated by Django 4.1.13 on 2024-03-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-createdAt',), 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='./static/img/'),
        ),
    ]
