# Generated by Django 4.1.13 on 2024-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='./static/uploaded/'),
        ),
    ]
