# Generated by Django 4.1.13 on 2024-04-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='./static/comments/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_order', to='products.product')),
            ],
        ),
    ]
