# Generated by Django 4.1.13 on 2024-04-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, upload_to='./static/comments/'),
        ),
    ]
