# Generated by Django 4.1.13 on 2024-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AddField(
            model_name='product',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='./static/img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='./static/img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='./static/img/'),
        ),
    ]
