# Generated by Django 4.1.13 on 2024-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.JSONField(default=list),
        ),
    ]
