# Generated by Django 4.1.13 on 2024-05-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='./static/reviews/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_order', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
