# Generated by Django 4.1.13 on 2024-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='isConfirm',
            field=models.BooleanField(default=False),
        ),
    ]
