# Generated by Django 4.1.13 on 2024-04-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderdetails_isconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='listProducts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(auto_created=True, max_length=100),
        ),
    ]
