# Generated by Django 4.1.13 on 2024-04-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_listproducts_alter_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
    ]
