# Generated by Django 4.1.13 on 2024-04-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.CharField(max_length=20),
        ),
    ]
