# Generated by Django 4.1.13 on 2024-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
    ]
