# Generated by Django 4.1.13 on 2024-04-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='orderDetailsId',
        ),
    ]
