# Generated by Django 4.1.13 on 2024-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_seller_orderdetails_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancel', 'Cancel'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
