# Generated by Django 4.1.13 on 2024-05-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shoppingCartId',
        ),
    ]
