# Generated by Django 4.1.13 on 2024-05-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_order_shoppingcartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shoppingCartId',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
