# Generated by Django 4.1.13 on 2024-05-21 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_status_alter_orderdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
