# Generated by Django 4.1.13 on 2024-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderdetails_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='size',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
